apiVersion: apps/v1
kind: Deployment
metadata:
  name: whitestack-demo
  labels:
    app: whitestack-demo
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whitestack-demo
  template:
    metadata:
      labels:
        app: whitestack-demo
        version: "1.0.0"
    spec:
      containers:
      - name: whitestack-demo
        image: whitestack-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: ENV
          value: "production"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

