apiVersion: v1
kind: Service
metadata:
  name: whitestack-demo-service
  labels:
    app: whitestack-demo
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: whitestack-demo
  sessionAffinity: ClientIP

